# run a workflow that runs the sync_files.py script
# should run on pull requests and pushes to master

# create another job that ensures typescript compiles correctly in the 'package' directory
name: Sync and Build Files
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync Files
        run: python3 sync_files.py
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Move directories
        run: cd package
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build


